### ISSUE TITLE
Greedy ImageSequence encoding

### ISSUE THREAD

**Issue by StripedMonkey** [jay3332/ril#19]
With the current interface, unless I'm missing something obvious, there is no way of eagerly encoding an image without an `ImageSequence<T>` of completed frames. This is somewhat of an issue, as frames get unreasonably large unreasonably quickly when dealing with raw RGB[A] frames as two seconds of 1080p frames is just a hair under a GB in size.

Ideally, I would like a way to push frames to be encoded, and avoid 30GB worth of frames sitting in memory before being encoded as a final step.

**Comment by jay3332** [comment]
added in ril v0.10 (https://github.com/jay3332/ril/commit/211eec45ccd01121df3452d767af6a35815b371b)
