### ISSUE TITLE
Cropping returning odd results.

### ISSUE THREAD

**Issue by hrbrmstr** [jay3332/ril#2]
First: this is a superb crate. I was able to convert https://github.com/hrbrmstr/rust-ipv4heatmap over to it (from the image crate) with ease, and the API is well-crafted.

I'm trying to use the `crop()` function as such:

```rust
use ril::{Image, Rgba};

fn main() {
  let mut image = Image::<Rgba>::open("assets/rustacean-flat-happy.png").unwrap();
  image.crop(0, 0, 512, 512);
  image.save_inferred("assets/cropped.png").unwrap();
}
```
This is the image being cropped:

![rustacean-flat-happy](https://user-images.githubusercontent.com/509878/190467443-3501b691-94b5-46d5-9975-23f65f603a78.png)

This is what crop produced:
![cropped](https://user-images.githubusercontent.com/509878/190467446-be3d9c0c-3a85-4c4f-8780-7fb7ee61cb7c.png)

I have a full "working" example I can push up to GH if that'll help.

**Comment by jay3332** [comment]
Can reproduce, I'll look into this later

**Comment by jay3332** [comment]
hmm, I can't reproduce this anymore locally, here is what I get:
![image](https://user-images.githubusercontent.com/40323796/190880545-1d16860a-0dc5-40aa-aab6-f468162e6c66.png)

> I have a full "working" example I can push up to GH if that'll help.
maybe this could help determine what leads to such a result.

**Comment by jay3332** [comment]
Could you maybe try using the version on GitHub? Use `ril = { git = "https://github.com/jay3332/ril" }` in dependencies

**Comment by hrbrmstr** [comment]
will do!

**Comment by hrbrmstr** [comment]
It seems to be fixed!

pre/post change to git `ril` (did a `cargo clean` prior):

![pre-crop2](https://user-images.githubusercontent.com/509878/190891742-7dd8c254-75ba-44fa-acca-df7edf4f4428.png)

![post-crop2](https://user-images.githubusercontent.com/509878/190891743-36a33aed-d227-43bc-8f8e-b28d4270b29d.png)

this is great! #ty!

**Comment by jay3332** [comment]
Good to hear!
