### ISSUE TITLE
Question: What is the scope of ril?

### ISSUE THREAD

**Issue by Quackdoc** [jay3332/ril#33]
Looking for something other then image-rs due to the jxl stuff, stumbled across this. What is the scope of ril in terms of codec support and features?

for instance

* will rill optionally support patent encumbered formats like HEIC (HEVC + HEIF) and the upcomming VVC based image format?
* Will rill support features like progressive image decoding? 

so on and so forth, I was wondering if there was a "todo" of sorts?

**Comment by jay3332** [comment]
1) I plan for RIL to support as many image formats as possible, but it seems like HEIC support in Rust is limited, so it will likely be a native implementation similar to WebP.

2) RIL already supports this via `ImageSequence::open` which returns an `impl FrameIterator`. An example is [here](https://github.com/jay3332/ril?tab=readme-ov-file#or-how-about-we-encode-each-frame-immediately-without-storing-them-in-memory)

3) There is a general list of image formats I plan on supporting before the stable release which is found in the README. There are definitely other features planned (e.g. filters and arbitrary rotation), but don't expect them super soon
