### ISSUE TITLE
Allow changing or getting gif framerates

### ISSUE THREAD

**Issue by jessicamaybe** [jay3332/ril#37]
Right now it doesn't seem like there is a way to deal with changing or fetching a gifs framerate, it'd be a nice feature to have.

**Comment by jay3332** [comment]
If you're talking about the delay between frames, that is supported. You can retrieve frame delays via `Frame::delay` (`FrameIterator` is a subtrait of `Iterator<Item = Frame>`), and you can set frame delays via `Frame::{with,set}_delay` and then encoding with an `ImageSequence`

**Comment by jessicamaybe** [comment]
Yep, that'll do it! Thanks!
